ORGAN_CHOICES = [('Pleura', 'Pleura'), 
    ('Pancreas', 'Pancreas'),
    ('Soft tissue', 'Soft tissue'),
    ('Peritoneum', 'Peritoneum'),
    ('Lung', 'Lung'),
    ('Liver', 'Liver'),
    ('Sinunasal', 'Sinunasal'),
    ('Unknown', 'Unknown'),
    ('Colon', 'Colon'),
    ('Adrenal gland', 'Adrenal gland'),
    ('Kidney', 'Kidney'),
    ('Small intestine', 'Small intestine'),
    ('Anal', 'Anal'),
    ('Thyroid', 'Thyroid'),
    ('Lung', 'Lung'),
    ('Ovary', 'Ovary'),
    ('Peritoneum', 'Peritoneum'),
    ('Bone', 'Bone'),
    ('Rectum', 'Rectum'),
    ('Appendix', 'Appendix'),
    ('Salivary Gland', 'Salivary Gland'),
    ('Testis', 'Testis'),
    ('Stomach', 'Stomach'),
    ('Thymus', 'Thymus'),
    ('Mediastinum', 'Mediastinum'),
    ('Cervix', 'Cervix'),
    ('Brain', 'Brain'),
    ('Cat', 'Cat'),
    ('Dog', 'Dog'),
    ('Mouse', 'Mouse'),
    ('Prostate', 'Prostate'),
    ('Breast', 'Prostate'),
    ('Esophagus', 'Esophagus'),
    ('Cell line', 'Cell line')]



TUMOR_CHOICES = [('CUP', 'CUP'),
    ('PDAC', 'PDAC'),
    ('Sarcoma', 'Sarcoma'),
    ('CRC', 'CRC'),
    ('SCC', 'SCC'),
    ('HCC', 'HCC'),
    ('Melanoma', 'Melanoma'),
    ('Carcinoma', 'Carcinoma'),
    ('Tumor', 'Tumor'),
    ('AmpullaryCA', 'AmpullaryCA'),
    ('NTRK', 'NTRK'),
    ('CCC', 'CCC'),
    ('EsophagusCA', 'EshophagusCA'),
    ('PapillaryCA', 'PapillaryCA'),
    ('ClearcellCA', 'ClearcellCA'),
    ('AppendixCA', 'AppendixCA'),
    ('Serous', 'Serous'),
    ('Mesothelioma', 'Mesothelioma'),
    ('NET', 'NET'),
    ('BreastCA', 'BreastCA'),
    ('Adenocarcinoma', 'Adenocarcinoma'),
    ('CRC', 'CRC'),
    ('Germ cell tumor', 'Germ cell tumor'),
    ('MMMT', 'MMMT'),
    ('Seminoma', 'Seminoma'),
    ('Thymom', 'Thymom'),
    ('MagenCA'), ('MagenCA'),
    ('Acinar cell Carcinoma', 'Acinar cell Carcinoma'),
    ('Adenoma', 'Adenoma'),
    ('Liver', 'Liver'),
    ('SCLC', 'SCLC'),
    ('Lymphoma', 'Lymphoma')
    ]

CONSENT_CHOICES = [('Yes', 'Yes'), 
    ('No', 'No')]